<?xml version="1.0"?>
<robot name="smartcar" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="length" value="0.02"/>
    <xacro:property name="radius" value="0.02"/>
    <xacro:property name="leng" value="0.25"/>
    <xacro:property name="width" value="0.16"/>
    <xacro:property name="height" value="0.05"/>

    <material name="black">
        <color rgba="0.3 0.2 0 1"/>
    </material>
    <material name="blue">  
        <color rgba="0 0 .8 1"/>  
    </material>  

    <xacro:macro name="wheel" params="LR FB sym1 sym2 sym3">
    <link name="${LR}_${FB}_wheel">
        <visual>
            <origin xyz="0.0 0.0 0" rpy="1.570 0.0 0.0"/>
            <geometry>
                <cylinder radius="${radius}" length="${length}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <inertial>  
            <origin  xyz="0 0 0"/>  
            <mass value="1" />  
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>  
        </inertial>
        <collision>  
            <origin  xyz="0 0 0" rpy="1.570 0 0"/>  
            <geometry>  
                <cylinder length=".02" radius="0.02"/>  
            </geometry>  
        </collision>  
    </link>
    <joint name="joint_${LR}_${FB}_wheel" type="continuous">
        <parent link = "base_link"/>
        <child link = "${LR}_${FB}_wheel"/>
        <origin xyz = "${sym1*(leng/2-0.05)} ${sym2*(width-length)/2} ${sym3*(radius)}" rpy = "0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <gazebo reference="${LR}_${FB}_wheel">
        <material>Gazebo/Gray</material>
    </gazebo>
    </xacro:macro>


    <link name="base_link">  
        <visual>  
        <geometry>  
            <box size="${leng} ${width} ${height}"/>  
        </geometry>  
        <origin rpy="0 0 0" xyz="0 0 ${radius+height/2}"/>  
        <material name="blue"/>  
        </visual>  
        <inertial>  
            <origin xyz="0 0 ${radius+height/2}"/>  
            <mass value="10" />  
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>  
        </inertial>
        <collision>  
            <origin rpy="0 0 0" xyz="0 0 ${radius+height/2}"/>  
            <geometry>  
                <box size="${leng} ${width} ${height}" />  
            </geometry>  
        </collision>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo> 
<!--
    <link name="base_footprint">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
            </visual>
        </link>
        <gazebo reference="base_footprint">
            <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0 0 ${-height/2}" rpy="0 0 0" />        
            <parent link="base_footprint"/>
            <child link="base_link" />
        </joint>-->


    <xacro:wheel LR="left" FB="front" sym1="1" sym2="1" sym3="1" />
    <xacro:wheel LR="left" FB="back" sym1="-1" sym2="1" sym3="1" />
    <xacro:wheel LR="right" FB="front" sym1="1" sym2="-1" sym3="1" />
    <xacro:wheel LR="right" FB="back" sym1="-1" sym2="-1" sym3="1" />
    <!--
    <transmission name="left_front_wheel_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_left_front_wheel" >
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint_left_front_wheel_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>-->

    <transmission name="right_front_wheel_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_right_front_wheel" >
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint_right_front_wheel_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <gazebo>
        <plugin name="differential_drive_controller" 
                filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>true</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <legacyMode>true</legacyMode>
            <leftJoint>joint_left_front_wheel</leftJoint>
            <rightJoint>joint_right_front_wheel</rightJoint>
            <wheelSeparation>${width-length}</wheelSeparation>
            <wheelDiameter>${2*radius}</wheelDiameter>
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>0.5</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic>
            <odometryFrame>odom</odometryFrame> 
            <odometryTopic>odom</odometryTopic> 
            <robotBaseFrame>base_link</robotBaseFrame>
        </plugin>
    </gazebo> 
<!--camera-->
<link name="camera_link">
            <inertial>
                <mass value="0.1" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                         iyy="0.01" iyz="0.0"
                         izz="0.01" />
            </inertial>

            <visual>
                <origin xyz=" 0 0 0 " rpy="0 0 0" />
                <geometry>
                    <box size="0.01 0.04 0.04" />
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <box size="0.01 0.04 0.04" />
                </geometry>
            </collision>
        </link>
        <gazebo reference="camera_link">
            <material>Gazebo/Black</material>
        </gazebo>
        <gazebo reference="camera_link">
            <sensor type="camera" name="camera_node">
                <update_rate>30.0</update_rate>
                <camera name="head">
                    <horizontal_fov>1.3962634</horizontal_fov>
                    <image>
                        <width>1280</width>
                        <height>720</height>
                        <format>R8G8B8</format>
                    </image>
                    <clip>
                        <near>0.02</near>
                        <far>300</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>
                <plugin name="gazebo_camera" filename="libgazebo_ros_camera.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>0.0</updateRate>
                    <cameraName>/camera</cameraName>
                    <imageTopicName>image_raw</imageTopicName>
                    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                    <frameName>camera_link</frameName>
                    <hackBaseline>0.07</hackBaseline>
                    <distortionK1>0.0</distortionK1>
                    <distortionK2>0.0</distortionK2>
                    <distortionK3>0.0</distortionK3>
                    <distortionT1>0.0</distortionT1>
                    <distortionT2>0.0</distortionT2>
                </plugin>
            </sensor>
        </gazebo>

      
    <joint name="camera_joint" type="fixed">
        <origin xyz="0.1 0 0.09" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>






</robot>